"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['../ui.py']
DATA_FILES = ['--iconfile']
OPTIONS = {'iconfile': '/Users/lucasmarandat/Documents/Perso/2020/pdf-add-blank-page-tmp/assets/icon.icns'}

setup(
    app=APP,
    name='Chepa',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
